### ISSUE TITLE
Defect Hunting - July 10-15

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1238]
- [x] Button issues - reported in #1237

- [x] do we have compact popover? There are some variables not being used [link](https://github.com/SAP/fundamental-styles/blob/a12ee3fe3dc0b472fbb6f0bb208577d95eac6000/src/popover.scss#L31) - the height variables are not being used

- [x] toolbar storybook missing #1245

- [x] combobox storybook missing #1245

- [x] context menu storybook missing #1245

- [x] multi input storybook missing #1245

- [x] time picker storybook missing #1245

- [x] input storybook missing #1245

**Comment by salarenko** [comment]
- [ ] Info label with icon missing border (icons issue)
![image](https://user-images.githubusercontent.com/17496353/87412245-18990000-c5c9-11ea-92a7-dd39b5141738.png)

**Comment by rengare** [comment]
- [ ] theme in IE 11:
![image](https://user-images.githubusercontent.com/10849982/87426913-43db1980-c5e0-11ea-9225-8348d526a852.png)
- [ ] storybook is super slow in IE 11 vs old documentation
