### ISSUE TITLE
Self-contained styles for all components

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-styles#136]
Making all components self-contained. 

Legend: 
`In Progress` - the component name has a link to the relevant GitHub issue 
`Ready for Review` - the component is ready to be reviewed 
`Completed` - the checkbox in front of the component name is checked.

- [x] Action Bar #211 `Completed`
- [x] Alert #97 
- [x] Badge #99 
- [x] Breadcrumb #100 
- [x] Button #60 #193 
- [x] Button-group #145 `Completed`
- [x] Button-split `Completed`
- [x] Calendar `Completed`
- [x] Combobox Input `Completed`
- [x] Contextual Menu `REMOVED`
- [x] Counter #134 `Complete`
- [x] Date Picker `REMOVED`
- [ ] Dropdown
- [x] Form #167 `in Progress` JENNA
- [x] Icon #147`Completed` 
- [X] Identifier #128 `Completed` 
- [x] Image #124 `Completed` 
- [x] Inline Help #146 `Completed`
- [x] Input Group #165 `In Progress` GREG
- [x] Label #102 `Completed`
- [x] Link #101 `Completed`
- [x] List Group #212  `Completed`
- [X] Loading Spinner #129  (to be removed once the replacement is ready)
- [ ] Localization Editor
- [x] Menu #158 `Completed`
- [ ] Modal #256 `Ready for Review` MARK
- [x] Multi Input `Completed`
- [x] Pagination #220 `Complete`
- [x] Panel #222 `Complete`
- [x] Panel-grid `Complete`
- [x] Popover #148 `Completed`
- [x] ~~Product-menu #266~~ `DONE`
- [x] ~~Product-switcher #265~~ `Ready for Review` DENO
- [x] Product-tile #160 `Completed`
- [ ] Search Input
- [ ] Shellbar
- [x] Side Navigation #131 `Completed`
- [x] Status Label #98 `Completed`
- [x] Table #278 `Completed`
- [X] Tabs #166 `Completed` 
- [x] Tile #149 `Completed`
- [x] Tile-grid `Spec Change for Layout Grid`
- [x] Time `Completed` MARK
- [x] Time Picker `REMOVED`
- [x] Token #132 `Completed` 
- [x] Toggle #213 `Completed`
- [x] Tree `Ready for Review` JENNA
- [X] ~~User Menu #247~~ `Removed`
- [ ] Overlay #291  `Ready for Review` GREG
- [x] Section #271 `DONE`
- [x] Page #273 `DONE`
