### ISSUE TITLE
Component Specs Sprint 45

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1416]
- [x] Cards - #3173
- [x] Formatted Text - #3174 - taken by Manju's team
- [ ] Object Number - #3175
- [ ] Icon  - 0.5/0.5 - #1572  Jedrzej
- [ ] Rating Indicator - #3176
- [ ] Carousel - #3177
- [ ] Wizard - 0/3 - Inna (styles implementation)
- [ ] Flexible Column Layout - 1/1 - Kasia
- [ ] MultiCombo - #1466 0 / 1 (Follow up with the designers)
- [x] Label - 0/0 - exists - follow up with Manju to confirm
- [ ] Object List Item - #1509 1/1
- [ ] Upload Collection - 1/2 - #1566 - Jedrzej
- [x] Action Sheet - 0/1 - #1537 - Jedrzej - Styles implementation

Total: 21 pd
