### ISSUE TITLE
Component Specs Sprint 46

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1418]
- [ ] Rich Text Editor - Michal - (1d/1d)
- [ ] Process Flow - Inna - WT...? (1sprint/5sprints) P.S. I'm not working on this :D
- [ ] Search Field - Inna - (1d/3d)
- [ ] Grid Table - Jedrzej (1d/5d)
- [ ] Badge on Button - Jedrzej - (1d/3d)
- [ ] Table Tree - Mike
- [ ] Overview Page - Mike

sample estimates - 1d styles spec/ 10d styles impl

**Comment by manjunathanagaraj** [comment]
Following components picked by by my team:
- Object Identifier(styles, core, platform)
- Slider (styles , core )
- Text(styles)
- Feed input + item (styles, core)
