### ISSUE TITLE
List Component improvements

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2063]
There are several issues related to list component. It is better if they are combined in 1 issue so we can tackle everything at the same time. Here is the list of those improvements needed:

### Done:
- [x] For "No Data" styles - Necessary styles are there - `--no-data` modifier
- [x] semantic indication in the beginning of the list - **I couldn't find it in any spec**
- [x] list Byline is changing its height when bottom border is added #1596 - I Can't reproduce it anymore
- [x] On touch of multi-select list item non fiori color is highlighted #1712 - On styles there is no way to make it work without JS. For NGX it works fine

#### Dnd Styles: - will be implemented in NGX (NA)
- [x] Drag and Drop styles - Can be taken from NGX 

#### Interractive states: - Jedrzej ( 1day )
- [x] Interactive States -Active/down state for non actionable item
- [x] Selection list with simple list item #1588 - `.is-selected` should work fine even on basic `fd-list__item`

#### Growing list: (1/2day) - Inna - https://github.com/SAP/fundamental-styles/pull/2099
- [x] growing list - TODO Intergration with busy-indicator

#### Byline: Mike ( 2days ) - https://github.com/SAP/fundamental-styles/pull/2074
- [x] wrapping behaviour - Missing in byline 
- [x] object status in standard list should be aligned on the right #1906 - Byline
- [x] list item counter - Done for standard list on styles, missing in byline list - `fd-list__item-counter`

#### Actions: (2days) - Jedrzej
- [x] [Buttons](https://wiki.wdf.sap.corp/wiki/display/visualcore/List+%28Fiori+3%29+-+Buttons?src=contextnavpagetreemode) 
- [x] [Deletion](https://wiki.wdf.sap.corp/wiki/display/visualcore/List+%28Fiori+3%29+-+Deletion?src=contextnavpagetreemode) 
- [x] Delete icon position is not middle in standard list with byline #1590 - There should be added example with centered button on byline list

#### Styles Inconsistency: (1day) - Inna
- [x] [Atachment List](https://wiki.wdf.sap.corp/wiki/display/visualcore/List+%28Fiori+3%29+-+Attachment+List) - [PR](https://github.com/SAP/fundamental-styles/pull/2103)
- [x] Group header got some issues with truncation - [PR](https://github.com/SAP/fundamental-styles/pull/2101)
![image](https://user-images.githubusercontent.com/26483208/104911132-aa276700-598a-11eb-8a99-87540a18bc47.png)
- [x] Navigation Indicator - Color Should be  `--sapList_SelectionBorderColor` - [PR](https://github.com/SAP/fundamental-styles/pull/2102)

The issues:
[#1906](https://github.com/SAP/fundamental-styles/issues/1906)
[#1712](https://github.com/SAP/fundamental-styles/issues/1712)
[#1596](https://github.com/SAP/fundamental-styles/issues/1596)
[#1590](https://github.com/SAP/fundamental-styles/issues/1590)
[#1588](https://github.com/SAP/fundamental-styles/issues/1588)
[#1399](https://github.com/SAP/fundamental-styles/issues/1399)
[#1398](https://github.com/SAP/fundamental-styles/issues/1398)
[#1334](https://github.com/SAP/fundamental-styles/issues/1334)
[#1333](https://github.com/SAP/fundamental-styles/issues/1333)
[#1112](https://github.com/SAP/fundamental-styles/issues/1112)
[#1110](https://github.com/SAP/fundamental-styles/issues/1110)
[#1109](https://github.com/SAP/fundamental-styles/issues/1109)

**Comment by JKMarkowski** [comment]
Styles missing:
- Navigation Indicator - Color Should be  `--sapList_SelectionBorderColor`;
