### ISSUE TITLE
Implement IconTabBar component with UniversalIconTabBar and Badge features

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2073]
- [ ] Single Click Area
- [ ] Two Click Areas
- [ ] Semantic tab bar (with icons and colors)
- [ ] Shell Navigation color delta
- [ ] Dropdown menu with/without separators
- [ ] IconTabBar with badges
- [ ] Badge inside dropdown meneu
