### ISSUE TITLE
Implement Tool Header Component

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2209]
The Tool Header is a control that is found in most SAP Cloud Platform products, most commonly as a part of the Tool Page Layout. The Tool Header inherits its functionality from the **OverflowToolbar** and its visual design from the **ShellBar**.

- [x] decide if we will re-use the ShellBar classes or create new ones for ToolHeader (naming, code) EDIT: decided to create a new component with new class names
- [x] over-styled controls
- [x] buttons and their states - The ToolHeader supports only text and icon buttons in their Default, Transparent, Back, and Up types. The Menu button is supported in its Emphasized, Default, and Transparent styles.
- [x] Texts, Titles, and Labels - The ToolHeader supports only single-line text and truncation. This applies to Texts, Titles, and Labels. Consider using small and normal size texts or title headings of H4, H5, H6. Avoid using text wrapping.
- [x] Icons - icons + background
- [na] Tabs - uses Horizontal Navigation - will be implemented as part of Horizontal Navigation
