### ISSUE TITLE
Combined issue for ShellBar/Navigation topic

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2212]
This is a combined ticket for all the issues related to the ShellBar/Navigation topic:

- [ ] [ShellBar migration to latest design #2208](https://github.com/SAP/fundamental-styles/issues/2208)
- [x] [Introduce User Menu in the ShellBar #1972](https://github.com/SAP/fundamental-styles/issues/1972) (DESIGN WIP)
- [x] [Implement IconTabBar component with UniversalIconTabBar and Badge features #2073](https://github.com/SAP/fundamental-styles/issues/2073)
- [x] [Implement Horizontal Navigation #2210](https://github.com/SAP/fundamental-styles/issues/2210)
- [x] [Implement Tool Header Component #2209](https://github.com/SAP/fundamental-styles/issues/2209)
- [x] [Implement Vertical Navigation #2211](https://github.com/SAP/fundamental-styles/issues/2211)
- [ ] Double check the latest navigation design and concept
