### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2271]
This is an epic that will collect all documentation improvements and issues.
- [ ] API improvements
- [ ] Examples and design improvements
- [ ] netlify is very slow/issues with cache
- [ ] Clean up examples with custom styling
 Examples: [Fixed Card Layout](https://fundamental-ngx.netlify.app/#/core/fixed-card-layout) there are inline stylings like `<div style="padding: 1rem; overflow: auto;">`

**Comment by InnaAtanasova** [comment]
This will be part of Version 1 task for each component.
