### ISSUE TITLE
Fundamental Website redesign and content update

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2304]
It would be great if we change the current website.
- [x] focus more on the most active parts of Fundamental Library(Styles and Angular)
- [x] answer the question `why would i use fundamental library`
- [x] add how to start section
- [x] add how to contribute secion
