### ISSUE TITLE
Status icons update and alignment

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2321]
The message status icons are updated (icon-error, icon-sys-enter-2, icon-alert, icon-information, icon-sys-help-2)
The goal of this epic is to check the updated design and identify any changes(including documentation and examples) on fundamental components:
- [ ] Message popover
- [ ] Button 
- [ ] toggle button
- [ ] Message box
- [ ] Message Strip
- [ ] Message View
- [ ] Micro Process Flow
- [ ] Process Flow
- [ ] Object Status
- [ ] Object Number
- [ ] Generic tile error state
- [ ] Value states states on OVP cards
- [ ] Icon tab bar (HC) 
- [ ] Progress indicator (HC)
