### ISSUE TITLE
BTP vs. Fiori

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2327]
- [x] Review BTP design
- [x] Identify the differences and evaluate the changes needed

Documentation Requests:
- [ ] buttons - regular buttons - update the documentation to map and reflect primary/secondary/tertiary vs. button types
- [ ] List item - show more/less - update the doc
- [ ] Vertical Nav - add examples with collapsed/expanded sections - update the doc

Visual Requests:
- [ ] buttons - toggle and segmented button - centred text, button width should be equal regardless of text length
- [ ] list - vertical spacing: should Fundamental match with BTP design to reduce vertical spacing for improved readability?
- [ ] card-based layout - vertical spacing:  should Fundamental match with BTP design to reduce vertical spacing for improved readability?

_To be implemented in Fundamental if needed_
- [ ] color picker - arrows design, few design diff. **design question**, missing in fundamentals
- [ ] Tabs - instance tab - to be implemented in fundamental
- [ ] wizard - embedding wizard in the dialog component
- [ ] list - in-place editing; show examples
- [ ] multi-input - new pattern introduced in BTP to fit five lines
- [ ] splitter; split layout

BTP Related:
- [ ] input examples in BTP: UI texts should reflect the semantic message
- [ ] switch - color differences/ width (awaiting response from BTP team)

Resolved:
- [x] timepicker - arrows up/down **design question**
- [x] select - arrow icons - two weights available
- [x] slider - ring size - two weights available
- [x] panel - slightly diff. design/padding - check with Fiori 3 design: two options: (a) having the line under the header (b) having the line under the section. both can be used
- [x] List item - avatar examples: avatar can be in either a circle or a rectangular shape, depends on use cases; in some cases it is flexible for the user to choose
- [x] wizard - text colors, spacing and line width, empty spacing
- [x] user menu - 2 additional icons in Fundamental: only exist in spec but never has the use case for it in implementation; badge design
- [x] calendar - the state which the date is on light blue block with dark blue border: not documented in Fundamental

**Comment by I546502** [comment]
For details on these requests, please refer to [this Figma file](https://www.figma.com/file/ToIXWKKNShFMOfO0MLGYlB/BTP-Analysis?node-id=0%3A1).

- [ ] button - regular button
<img width="1433" alt="Screen Shot 2021-05-18 at 2 24 45 PM" src="https://user-images.githubusercontent.com/83095564/118725541-ee196400-b7e4-11eb-82d8-9de789aeaf9e.png">

- [ ] button - toggle and segmented button
<img width="1435" alt="Screen Shot 2021-05-18 at 2 25 01 PM" src="https://user-images.githubusercontent.com/83095564/118725544-ef4a9100-b7e4-11eb-8eb4-db2459b305c8.png">

**Comment by droshev** [comment]
@hanjunt @kari-leg let's discuss this and decide how to proceed.

**Comment by droshev** [comment]
closing this as we are shifting towards Fiori Horizon
