### ISSUE TITLE
Review and update all components to the latest Horizon spec and prepare the components for v.1 release

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#3962]
The goal is to go over every component and apply the latest design. we can agree on a certain timestamp.
We should test and target all browsers(Chrome, FF, Safari, and Edge)

Please add your name to the component before you start working on it and add a link to the PR once you are done with it. This will help us keep track of the progress. 

**Scroll to the bottom to see the requirements that have to be met as part of the version 1.0.0 release.**

- [ ] Action Bar
- [ ] Action Sheet
- [ ] Avatar
- [ ] Avatar Group
- [ ] Bar
- [ ] Breadcrumb
- [ ] Busy Indicator
- [ ] Button 
- [ ] Calendar
- [ ] Card
- [ ] Carousel
- [ ] Code
- [ ] Counter
- [ ] Dialog
- [ ] Feed Input
- [ ] Feed List and Item
- [ ] File Uploader
- [ ] Generic Tiles
- [ ] Grid List
- [ ] Grid List - Selection
- [ ] Icon Tab Bar
- [ ] Icons
- [ ] Illustrated Message
- [ ] Info Label 
- [ ] Link
- [ ] List - Standard
- [ ] List - Byline
- [ ] Menu 
- [ ] Message Box
- [ ] Message Page
- [ ] Message Popover
- [ ] Message Strip
- [ ] Message Toast
- [ ] Micro Process Flow
- [ ] Notifications
- [ ] Object Identifier
- [ ] Object List
- [ ] Object Marker
- [ ] Object Number
- [ ] Object Status
- [ ] Pagination
- [ ] Panel
- [ ] Popover 
- [ ] Product Switch
- [ ] Progress Indicator
- [ ] Quick View
- [ ] Rating Indicator
- [ ] Scrollbar
- [ ] Select
- [ ] Shellbar
- [ ] Slider  
- [ ] Splitter
- [ ] Status Indicator
- [ ] Step Input
- [ ] Switch
- [ ] Table 
- [ ] Text
- [ ] Time
- [ ] Title
- [ ] Token
- [ ] Tool Header
- [ ] Toolbar
- [ ] Tree
- [ ] Upload Collection
- [ ] User Menu
- [ ] Vertical Navigation
- [ ] Wizard

Forms
- [ ] Checkbox
- [ ] Field Set
- [ ] Form Grid
- [ ] Form Group
- [ ] Form Header
- [ ] Form Item
- [ ] Form Label
- [ ] Form Message
- [ ] Input Group
- [ ] Input
- [ ] Radio
- [ ] Textarea

Layouts
- [ ] Dynamic Page
- [ ] Dynamic Side Content
- [ ] Fixed Card Layout
- [ ] Flexible Column
- [ ] Layout Grid
- [ ] Layout Panel
- [ ] Page Footer
- [ ] Page
- [ ] Resizable Card Layout
- [ ] Section

Patterns
- [ ] Combobox Input
- [ ] Contextual Menu
- [ ] Date Picker
- [ ] Horizontal Navigation
- [ ] Multi ComboBox
- [ ] Multi Input
- [ ] Time Picker

============================== STYLE GUIDE TASK ===============================
To DO: Create a style guide that includes naming conventions, best practices, standards, etc. that are used in the library and that will help with onboarding new developers or external contributors. This will also help the PR review process by automating some of these checks.

Some examples of good style guides:
- https://github.com/airbnb/javascript/tree/master/react
- https://angular.io/guide/styleguide
- https://vuejs.org/v2/style-guide/

Please use this page: https://github.com/SAP/fundamental-styles/wiki/Fundamental-styles-Style-Guide

Once it's finalized it will be moved to a readme file and published officially.

============================== VERSION 1.0.0 ===============================

The following tasks should be done to consider this component as ready for version 1.0.0 release. 

*Please make sure that all tasks are completed before opening the PR. Leave comments for the tasks that for some reason cannot be completed or are blocked.

- [ ] design review - compare the properties defined in the design specs with the ones from the implementation. 
Must be done for all themes: 
    - [ ] Quartz Light
    - [ ] Quartz Dark
    - [ ] Quartz HCW
    - [ ] Quartz HCB
    - [ ] Morning Horizon
    - [ ] Evening Horizon
    - [ ] Horizon HCW
    - [ ] Horizon HCB
- [ ] Bug fixing related to the design review
- [ ] Check the component implementation in Fund-ngx and adapt the local css (bring the custom css in fund-styles), Fund-ngx should have only Angular related css code. 
- [ ] Code base clean-up
   - [ ] review the existing code
   - [ ] evaluate the use of !important and check if the same result can be achieved with specificity
   - [ ] see if the code can be simplified by using mixins, placeholders, variables
   - [ ] see if a component mixin (for example a mixin added in the Menu file) can be reused in other component by added parameters or using `@content` and move it to the global mixin file
   - [ ] use variables instead of overwriting the rules for modifier classes (ex. compact modifier)
   - [ ] remove deprecated code or code we don't use
- [ ] documentation for the component
    - [ ] API - check if all modifier classes are documented (states, compact/cosy, etc.)
    - [ ] Examples review - check if the existing examples cover all cases we have. We need to add examples for the states of the components (active, hover, disabled, etc.) so we can detect issues with Chromatic
    - [ ] Add links to the UX guidelines and more info about when to use or not use the component, etc.
- [ ] a11y - make sure the component follows the a11y guidelines in terms of markup, aria attributes, focus, etc.
- [ ] focus - https://github.com/SAP/fundamental-styles/issues/3541
- [ ] review self-contain concept - a component should not modify the properties of another component. Each component should be able to live in isolation, aka not depending on any other component. Modifier classes should be added in such cases.
- [ ] browser testing - the component should look like and behave the same way in all supported by us browsers.

**Comment by platon-rov** [comment]
It should be done within doing v1 components preparations. You refactor - you check component's look accordingly to the specs.

**Comment by InnaAtanasova** [comment]
https://github.com/SAP/fundamental-styles/issues/3168

**Comment by InnaAtanasova** [comment]
https://github.com/SAP/fundamental-styles/issues/3302

**Comment by InnaAtanasova** [comment]
https://github.com/SAP/fundamental-styles/issues/3541
