### ISSUE TITLE
UXC Updates

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#4260]
UXC product standard got some updates (e.g in shellbar). We need to: 
- [x] review them
- [x] list the changes
- [x] implement the changes 

-----------------------------------------------------------------------------------------------------------------------

- [x] User Menu - **new component**. We have User Menu from Visual Core but we need one for BTP, which looks different. User Menu for Visual Core also needs to be updated  (5d) https://github.com/SAP/fundamental-styles/issues/4313
- [x] Button Extensions - **new features** and _updates_  (3-4d) https://github.com/SAP/fundamental-styles/issues/4314
       - icons on both sides
       - primary, secondary & transparent buttons need to be updated (visual and interaction states)
       - nested button (new)
       - badge on button
- [x] Menu - **new component** (8-10d) https://github.com/SAP/fundamental-styles/issues/4315
       - menu item
       - responsiveness
       - containers (dropdown, popover)
- [x] Tool Header - _update_ (4-5d) https://github.com/SAP/fundamental-styles/issues/4316
      - structure/anatomy
      - search
      - responsiveness
- [x] Navigation - _update_ (10-14d)
      - [ ] Horizontal https://github.com/SAP/fundamental-styles/issues/4317
      - [ ] Vertical https://github.com/SAP/fundamental-styles/issues/4318
- [x] Tool Layout - **new component** (4d) https://github.com/SAP/fundamental-styles/issues/4319
- [x] Notifications  - **new component** (5d) https://github.com/SAP/fundamental-styles/issues/4320
- [x] Search  - **new component** (needed for ShellBar) (4-5d) https://github.com/SAP/fundamental-styles/issues/4321
- [x] Avatar Extensions  - **new features** (needed for Notifications) (1d) https://github.com/SAP/fundamental-styles/issues/4322
- [x] Instance Switch  - **new component** (3-4d) https://github.com/SAP/fundamental-styles/issues/4323
