### ISSUE TITLE
Horizon 2023 Project

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#4403]
List of components to be created/updated:
- [ ] Avatar #4366 
- [ ] Avatar Group #4367 
- [ ] Busy Indicator #4399 
- [ ] Buttons (Standard, Menu Button, Split Button, Segmented Button, Toggle Button) #4368 
- [ ] Calendar #4369 
- [ ] Card #4370 
- [ ] Carousel #4371 
- [ ] Checkbox #4372 
- [ ] Combobox #4373 
- [ ] Datepicker #4374 
- [ ] Dialog #4375 
- [ ] Dynamic Page #4400 
- [ ] Dynamic Side Content #4376 
- [ ] Flexible Column Layout #4401 
- [ ] Icon Tab Bar #4394
- [ ] Input #4377 
- [ ] Label #4378 
- [ ] Link #4379 
- [ ] List #4380 
- [ ] Menu #4381 
- [ ] Message Strip #4383 
- [ ] Multi Combobox #4384 
- [ ] Multi Input #4385 
- [ ] Page #4386 
- [ ] Progress Indicator #4388 
- [ ] Radio Button #4389 
- [ ] Range Slider #4390 
- [ ] Select #4391  
- [ ] Sllider #4392 
- [ ] Step Input #4393 
- [ ] Switch #4402 
- [ ] Table #4395 
- [ ] Tag #4396 
- [ ] Title #4397 
- [ ] Toolbar #4398
