### ISSUE TITLE
Side Navigation - refactoring

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#560]
Side navigation needs an overflow menu for items that don't fit in the Main Section

The side navigation(a.k.a. Vertical Navigation design changed a bit)
What needs to be done:
- [ ] review the design and plan tasks (1day)
   - [x] design has been reviewed and the questions are added to the agenda of the next design review meeting
   - [ ] implement Horizontal Navigation which depends on UniversalIconTabBar
   - [ ] refactor Side Navigation (vertical navigation) 
       - [ ] condensed mode second level indicator
       - [ ] second level expanded stated re-styling
       - [ ] nesting levels indentation spacings
       - [ ] visible second level styling
   - [ ] new feature - navigated item
- [ ] refactoring task
- [ ] bring it to ngx..

**Comment by droshev** [comment]
it will be tackled as part of the Vertical navigation
