### ISSUE TITLE
Defect Hunting - May 2-4, 2020

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#938]
List of issues found during the defect hunting on May 2nd-4th, 2020

- [x] documentation bleeding into list (Gracjan) #941
![Screen Shot 2020-05-02 at 10 49 03 PM](https://user-images.githubusercontent.com/4380815/80897494-49a2ad80-8cc7-11ea-8b11-7ae5747161f3.png)
![Screen Shot 2020-05-02 at 10 48 57 PM](https://user-images.githubusercontent.com/4380815/80897495-4a3b4400-8cc7-11ea-8087-0bddb178e07c.png)
- [x] List item focus looks not correct(3 pixels inside) - I'm Sure that 3px focus is correct [Jedrzej]
List
![Screen Shot 2020-05-02 at 10 54 23 PM](https://user-images.githubusercontent.com/4380815/80897557-0137bf80-8cc8-11ea-9508-94f77b14c0ed.png)
![image](https://user-images.githubusercontent.com/26483208/80959599-71009400-8e07-11ea-982d-d6a0d880586c.png)

Menu
![Screen Shot 2020-05-02 at 10 54 13 PM](https://user-images.githubusercontent.com/4380815/80897556-fd0ba200-8cc7-11ea-8a92-e2f9a7b73e5a.png)

- [x] Side Navigation RTL the arrow indicating nested levels is on the wrong side (Gracjan) #946
![Screen Shot 2020-05-02 at 11 01 38 PM](https://user-images.githubusercontent.com/4380815/80897648-f9c4e600-8cc8-11ea-9a89-2e8a66742640.png)

- [x] Select RTL - button is off - Jedrzej https://github.com/SAP/fundamental-styles/pull/939
![Screen Shot 2020-05-02 at 11 03 01 PM](https://user-images.githubusercontent.com/4380815/80897655-1e20c280-8cc9-11ea-84be-3664a60c1df0.png)

- [x] Shellbar > Avatar has wrong size(too wide) - Jedrzej https://github.com/SAP/fundamental-styles/pull/940
![Screen Shot 2020-05-02 at 11 13 20 PM](https://user-images.githubusercontent.com/4380815/80897790-9fc52000-8cca-11ea-902c-f08e805686c9.png)

- [x] Popover without arrow next to input - extra padding - Jedrzej **To Discuss**
![Screen Shot 2020-05-02 at 11 15 37 PM](https://user-images.githubusercontent.com/4380815/80897819-e61a7f00-8cca-11ea-8820-1183b35a013e.png)
![image](https://user-images.githubusercontent.com/26483208/80959394-094a4900-8e07-11ea-85bf-3474ae776f97.png)

- [x] Menu (nested level) in RTL has a horizontal scrollbar - Michal #944
![Screen Shot 2020-05-02 at 11 18 38 PM](https://user-images.githubusercontent.com/4380815/80897868-588b5f00-8ccb-11ea-919c-fef5ac59ec2c.png)

- [x] Avatar with zoom icon - RTL - the icon still stays in the right side - Michal #947
![Screen Shot 2020-05-02 at 11 22 04 PM](https://user-images.githubusercontent.com/4380815/80897923-d485a700-8ccb-11ea-993a-1f5fbc6669ce.png)
![Screen Shot 2020-05-02 at 11 21 54 PM](https://user-images.githubusercontent.com/4380815/80897924-d51e3d80-8ccb-11ea-9230-a92938dcbb7c.png)

**Comment by JKMarkowski** [comment]
Datepicker should have new markup
![image](https://user-images.githubusercontent.com/26483208/80950814-df892600-8df6-11ea-8414-f9ea88b22bde.png)

**Comment by droshev** [comment]
shellbar > mega menu on mobile is broken
![Screen Shot 2020-05-04 at 11 19 54 AM](https://user-images.githubusercontent.com/4380815/80984307-af905180-8dfb-11ea-8190-933253ad11b8.png)

**Comment by droshev** [comment]
Calendar Week Letter is still off:
![Screen Shot 2020-05-04 at 10 11 19 PM](https://user-images.githubusercontent.com/4380815/81029809-586a9b00-8e54-11ea-98af-aeaafd4f1c4f.png)

**Comment by rengare** [comment]
IE 11 all inputs have `X` button
![image](https://user-images.githubusercontent.com/10849982/81065972-ae832100-8edc-11ea-9fe7-be530d5d8e7e.png)

**Comment by rengare** [comment]
- [ ] **Number input should be deprecated and ?**
![image](https://user-images.githubusercontent.com/10849982/81074885-e8a6ef80-8ee9-11ea-9820-ada1c85bc0c8.png)

**Comment by stefanoScalzo** [comment]
@rengare cannot reproduce font issue on VM 
![Screen Shot 2020-05-05 at 10 14 11 AM](https://user-images.githubusercontent.com/50607147/81076080-348d7080-8eb9-11ea-99ff-e5a033f82fec.png)
![Screen Shot 2020-05-05 at 10 14 17 AM](https://user-images.githubusercontent.com/50607147/81076082-35260700-8eb9-11ea-82e1-cfca1cf426e8.png)

**Comment by JKMarkowski** [comment]
![image](https://user-images.githubusercontent.com/26483208/81076319-d037d480-8eeb-11ea-8e45-35237b8b01fe.png)

**Comment by rengare** [comment]
- [ ] message box examples are not centered in IE 11 (as in other browsers)
![image](https://user-images.githubusercontent.com/10849982/81119599-62ab9880-8f2b-11ea-8d88-fb4c3104a232.png)
- [ ] Product switch RTL mode broken
![image](https://user-images.githubusercontent.com/10849982/81119631-71924b00-8f2b-11ea-8b23-5833bb61f363.png)
![image](https://user-images.githubusercontent.com/10849982/81119644-7b1bb300-8f2b-11ea-9d40-fb7e20d8bd33.png)
- [ ] IE 11 selected border in time component is missing
![image](https://user-images.githubusercontent.com/10849982/81119694-9686be00-8f2b-11ea-8497-9d0035735a86.png)

**Comment by droshev** [comment]
Another round from me:
- [ ] shellbar example with collapsible menu (mobile/tablet resolution) click on the `...` menu and a bottom border appears
![Screen Shot 2020-05-05 at 10 57 44 PM](https://user-images.githubusercontent.com/4380815/81134861-0e50ea80-8f24-11ea-97e5-ac6ec956a545.png)

**Comment by mikerodonnell89** [comment]
List RTL has extra space on the right causing the left to overflow its container
![Screen Shot 2020-05-06 at 9 00 19 AM](https://user-images.githubusercontent.com/2471874/81192993-1a669780-8f78-11ea-8980-134abfc41cca.png)

Causes problems in other components as well such as this list in the select dialog
![Screen Shot 2020-05-06 at 8 55 00 AM](https://user-images.githubusercontent.com/2471874/81192372-61a05880-8f77-11ea-86e9-98145b521e70.png)

**Comment by mikerodonnell89** [comment]
Dialog header and title together?  I have not seen this in the specs
![Screen Shot 2020-05-06 at 9 23 56 AM](https://user-images.githubusercontent.com/2471874/81195688-6bc45600-8f7b-11ea-9bcf-b01a46241b6c.png)

Also should dialog resize handle change sides in RTL?
![Screen Shot 2020-05-06 at 9 25 09 AM](https://user-images.githubusercontent.com/2471874/81195773-85fe3400-8f7b-11ea-8989-4576939b59e1.png)

**Comment by mikerodonnell89** [comment]
Notification - I don't think this little ellipses should be all the way out here
![Screen Shot 2020-05-06 at 9 28 02 AM](https://user-images.githubusercontent.com/2471874/81196462-4be16200-8f7c-11ea-8b65-23dbf88bc8a4.png)

**Comment by mikerodonnell89** [comment]
Object status - margin on the wrong side in RTL
![Screen Shot 2020-05-06 at 9 32 13 AM](https://user-images.githubusercontent.com/2471874/81196623-864aff00-8f7c-11ea-952a-cd6f03c62a58.png)

**Comment by mikerodonnell89** [comment]
Status indicator - margin on the wrong side and "available" text in the wrong spot
![Screen Shot 2020-05-06 at 9 47 55 AM](https://user-images.githubusercontent.com/2471874/81198454-babfba80-8f7e-11ea-89b2-27603873fcad.png)
